name: CI
on: [push, pull_request]

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
      - run: cd app_flutter && flutter pub get
      - run: cd app_flutter && flutter test

  flask-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: cd server && pip install -r requirements.txt
      - run: cd server && pytest
